server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
  client:
    register-with-eureka: false
    fetch-registry: false
    disable-delta: true

