
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        connection:
          characterEncoding: utf-8
          Charset: utf-8
          useUnicode: true
        default_batch_fetch_size: 100
        jdbc.lob.non_contextual_creation: true
    defer-datasource-initialization: true
